export type MTR_Stock = {
  RecNo: number;
  StockCode: string;
  BarCode: string;
  Description: string;
  Unit: string;
  Color: string;
  Size: string;
  Cost: number;
  SRP: number;
  WholeSale: number;
  Vatable: boolean;
  Discount: number;
  SupplierCode: string;
  BrandCode: string;
  DepartmentCode: string;
  KindCode: string;
  LocationCode: string;
  CategoriesCode: string;
  SubCategoriesCode: string;
  Packing: string;
  OnhandQty: number;
  ReorderQty: number;
  Image: { type: string; data: number[] };
  STOCKType: string;
  PackageTAX: number;
  PackageINCENTIVE: number;
  PackageCENTER: number;
  PackageUNI: number;
  PackageMARKETING: number;
  PackageFREIGHT: number;
  PackageSTOCKIST: number;
  PackageQTYTODEDUCT: number;
  Remarks: string;
  Deleted: boolean;
  Status: string;
};
